
# Site settings
title: Rotaract Bangalore East
subtitle: "Unite. Rise. Empower"
url: "https://3190rbe.org" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
timezone: Asia/Kolkata

# Build settings
markdown: kramdown
# highlighter: rouge
permalink: blog/:year/:month/:day/:title/
paginate: 4
paginate_path: blog/page-:num/

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

collections:
  donations:
    output: true
    # permalink: /:path/

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
  
# Archives
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    category: '/blog/:name/'
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    tag: '/blog/tag-:name/'

include:
  - _redirects